// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIEOG4v8qOAJwghEfzLLQ9-R9W1RsoUI',
    appId: '1:809780982207:web:fde911e111da805557310a',
    messagingSenderId: '809780982207',
    projectId: 'e-money-7568e',
    authDomain: 'e-money-7568e.firebaseapp.com',
    storageBucket: 'e-money-7568e.firebasestorage.app',
    measurementId: 'G-J7BLM4Q856',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw0hdUirqPA476PNpV6c2wob1IpsJJ3B0',
    appId: '1:809780982207:android:e12cf0fa830c07a457310a',
    messagingSenderId: '809780982207',
    projectId: 'e-money-7568e',
    storageBucket: 'e-money-7568e.firebasestorage.app',
  );
}
